### ISSUE TITLE
There are three compiler warnings.

### ISSUE THREAD

**Issue by MasaruKitajima** [k-lpmg/RealmWrapper#11]
Every waring happens in `RealmManageable.swift` and same warning.

It says

> 'public' modifier is redundant for instance method declared in a public extension

It's not a big issue, but if fixed, appreciated.

**Comment by k-lpmg** [comment]
@MasaruKitajima 

I released version 1.3.0 that fixes the issue.

**Comment by MasaruKitajima** [comment]
@k-lpmg Thank you so much!
