### ISSUE TITLE
Is it possible apply this approach when Realm classes contains properties of another Realm classes?

### ISSUE THREAD

**Issue by unsophisticatedSwiftDev** [k-lpmg/RealmWrapper#12]
Did I get it right - this lib is virtually useless when Classes in Realm schema contains another Realm Classes?

**Comment by k-lpmg** [comment]
Hi @unsophisticatedSwiftDev 

I don't exactly understand `Realm schema contains another Realm Classes?`.
Can you explain it with example code?

**Comment by hamzaozturk** [comment]
You need to specify classes in your class extends RealmManageable.

You have a Task object and User object can have multiple task objects.
```
@objcMembers
class Task: Object {
    dynamic var id: String?
    dynamic var name: String?
    
    override static func primaryKey() -> String? {
        return "id"
    }
}
```

```
@objcMembers
class User: Object {
.
.
    let taskList = List<Task>()
    
.
.
}
```

In your UserRealmManager class, return the class objects you need.

```
    var objectTypes: [Object.Type]? {
        return [User.self, Task.self]
    }
```

**Comment by unsophisticatedSwiftDev** [comment]
No matter
