### ISSUE TITLE
Object property is unreachable in the realm result

### ISSUE THREAD

**Issue by waltcow** [k-lpmg/RealmWrapper#4]
Hi. I have some question about the realm result property,  this is my first time to use realm 

```swift
struct UserRealmProxy<RealmManager: UserRealmManager>: RealmProxiable {
   func getUser(_ userId: Int) -> User? {
        let result: RealmQuery<User> = query(filter: "id == \(userId)", sortProperty: "id", ordering: .ascending)
        return result.results.first
    }
}
    
```
When my service code want to fetch **user** from realm, the result is not nil, but the property from this realm object is still unreachable(empty) in the view render process.  it's so weird.

**Comment by k-lpmg** [comment]
Hi @waltcow 
I don't understand "realm object is still unreachable(empty) in the view render process".

Does the count of result continue to be 0?

**Comment by waltcow** [comment]
```swift
   func getTweets(spaceId: Int, limit: Int = 15) -> [Tweet] {
        let result: RealmQuery<Tweet> = query(filter: "spaceId == \(spaceId)", sortProperty: "id", ordering: .ascending)
        var data = [Tweet]()
        for i in 0 ..< min(limit, result.count) {
            data.append(result[i])
        }
        
        return data
    }
```
fetch result from realm 

![image](https://user-images.githubusercontent.com/3941174/51597409-2589e580-1f36-11e9-8ea1-054e433bc225.png)

cast model to  viewModel in a dictionary key key model id

![image](https://user-images.githubusercontent.com/3941174/51597516-62ee7300-1f36-11e9-98e6-842c471826e3.png)

problem is the realm model property is still unreadable though i try to access it

**Comment by waltcow** [comment]
```swift
class Tweet: Object, Mappable {
   @objc var id: Int = -1
   @objc  spaceId: Int = -1
   @objc  var content: String?
   @objc  var userId: Int = -1
   ....
}
```
After i change my model definition to the follow,  it works fine.

```swift

@objcMembers
class Tweet: Object, Mappable {
    dynamic var id: Int = -1
    dynamic var spaceId: Int = -1
    dynamic var content: String?
    dynamic var userId: Int = -1
   ....
}
```
