### ISSUE TITLE
RealmSwift 3.17.1 has changed UpdatePolicy

### ISSUE THREAD

**Issue by MasaruKitajima** [k-lpmg/RealmWrapper#9]
In the previous versions, `realm.add(users, update: true)` was right, but for the 3.17.1, we must choose options `update` from

 - `error`
 - `modified`
 - `all`

So, it's like `realm.add(users, update: .all)` for an instance.

Please refer further details at [RealmSwift Doc](https://realm.io/docs/swift/latest/api/Classes/Realm/UpdatePolicy.html)

**Comment by k-lpmg** [comment]
Hi @MasaruKitajima 

Thank you for your information.
I updated realm-cocoa version in Example and README.md (#10)

**Comment by MasaruKitajima** [comment]
@k-lpmg Thank you for your quick actions.
Much appreciated.
